/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Renders_SoftTex_hpp
#define LDL_Renders_SoftTex_hpp

class LDL_TextureSoftware
{
public:
	LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t* pixels, uint8_t bytesPerPixel);
	LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t bytesPerPixel);
	LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t* pixels, LDL_Palette* palette);
	LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t* pixels, LDL_Palette* palette, LDL_Alpha* alpha);
	~LDL_TextureSoftware();
	void Copy(const LDL_Vec2i& dstPos, const LDL_Vec2i& srcSize, uint8_t* pixels, uint8_t bytesPerPixel);
	void Copy(const LDL_Vec2i& dstPos, LDL_Surface* surface, const LDL_Vec2i& srcSize);
	const LDL_Vec2i& Size();
	const LDL_Vec2i& Quad();
	LDL_Surface* GetSurface();
private:
	LDL_Vec2i   _size;
	LDL_Vec2i   _quad;
	LDL_Alpha   _alpha;
	LDL_Surface _surface;
};

#ifdef LDL_IMPLEMENTATION
LDL_TextureSoftware::LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t* pixels, uint8_t bpp) :
	_surface(size, size, bpp)
{
	LDL_ASSERT(size.x >= 0);
	LDL_ASSERT(size.y >= 0);
	LDL_ASSERT(pixels != NULL);
	LDL_ASSERT(bpp >= 1 && bpp <= 4);

	memcpy(_surface.Pixels(), pixels, size.x * size.y * bpp);
}

LDL_TextureSoftware::LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t bpp) :
	_surface(size, size, bpp)
{
	LDL_ASSERT(size.x >= 0);
	LDL_ASSERT(size.y >= 0);
	LDL_ASSERT(bpp >= 1 && bpp <= 4);
}

LDL_TextureSoftware::LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t* pixels, LDL_Palette* palette) :
	_surface(size, size, pixels, palette)
{
}

LDL_TextureSoftware::LDL_TextureSoftware(const LDL_Vec2i& size, uint8_t* pixels, LDL_Palette* palette, LDL_Alpha* alpha) :
	_surface(size, size, pixels, palette, alpha)
{
}

LDL_TextureSoftware::~LDL_TextureSoftware()
{
}

void LDL_TextureSoftware::Copy(const LDL_Vec2i& dstPos, const LDL_Vec2i& srcSize, uint8_t* pixels, uint8_t bpp)
{
	LDL_ASSERT(dstPos.x >= 0);
	LDL_ASSERT(dstPos.y >= 0);
	LDL_ASSERT(srcSize.x >= 0);
	LDL_ASSERT(srcSize.y >= 0);
	LDL_ASSERT(pixels != NULL);
	LDL_ASSERT(bpp >= 1 && bpp <= 4);
}

void LDL_TextureSoftware::Copy(const LDL_Vec2i& dstPos, LDL_Surface* surface, const LDL_Vec2i& srcSize)
{
	LDL_ASSERT(dstPos.x >= 0);
	LDL_ASSERT(dstPos.y >= 0);
	LDL_ASSERT(srcSize.x >= 0);
	LDL_ASSERT(srcSize.y >= 0);
	LDL_ASSERT(surface != NULL);
}

const LDL_Vec2i& LDL_TextureSoftware::Size()
{
	return _size;
}

const LDL_Vec2i& LDL_TextureSoftware::Quad()
{
	return _quad;
}

LDL_Surface* LDL_TextureSoftware::GetSurface()
{
	return &_surface;
}
#endif

#endif
