/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Alpha_hpp
#define LDL_Alpha_hpp

class LDL_Alpha
{
public:
	LDL_Alpha();
	LDL_Alpha(const LDL_Color& color);
	LDL_Alpha(uint8_t index);
	bool IsAlpha();
	const LDL_Color& Color() const;
	uint8_t Index() const;
private:
	bool      _isAlpha;
	LDL_Color _color;
};

#ifdef LDL_IMPLEMENTATION
LDL_Alpha::LDL_Alpha() :
	_isAlpha(false)
{
}

LDL_Alpha::LDL_Alpha(const LDL_Color& color) :
	_isAlpha(true),
	_color(color)
{
}

LDL_Alpha::LDL_Alpha(uint8_t index) :
	_isAlpha(true),
	_color(index, 0, 0)
{
}

bool LDL_Alpha::IsAlpha()
{
	return _isAlpha;
}

const LDL_Color& LDL_Alpha::Color() const
{
	return _color;
}

uint8_t LDL_Alpha::Index() const
{
	return _color.r;
}
#endif

#endif
