/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Windows_Assert_hpp
#define LDL_Windows_Assert_hpp

void LDL_Assert(bool condition, const char* description, const char* file, size_t line, const char* detail, const char* verbose);

#define LDL_ASSERT(condition)                          LDL_Assert(condition, #condition, __FILE__, __LINE__, "", "")
#define LDL_ASSERT_DETAIL(condition, detail)           LDL_Assert(condition, #condition, __FILE__, __LINE__, detail, "")
#define LDL_ASSERT_VERBOSE(condition, detail, verbose) LDL_Assert(condition, #condition, __FILE__, __LINE__, detail, verbose)

#ifdef LDL_IMPLEMENTATION
void LDL_Assert(bool condition, const char* description, const char* file, size_t line, const char* detail, const char* verbose)
{
	if (!condition)
	{
		const size_t bufferMax = 128;
		char buffer[bufferMax];
		LDL_BytesClear(buffer, 0, bufferMax);

		LDL_CharsConcat(buffer, "Assert ", bufferMax);
		LDL_CharsConcat(buffer, "Description: ", bufferMax);
		LDL_CharsConcat(buffer, description, bufferMax);
		LDL_CharsConcat(buffer, " File: ", bufferMax);
		LDL_CharsConcat(buffer, file, bufferMax);

		LDL_Converter conv;
		LDL_CharsConcat(buffer, " Line: ", bufferMax);
		LDL_CharsConcat(buffer, conv.Convert(line), bufferMax);

		LDL_CharsConcat(buffer, " Detail: ", bufferMax);
		LDL_CharsConcat(buffer, detail, bufferMax);

		LDL_CharsConcat(buffer, " Verbose: ", bufferMax);
		LDL_CharsConcat(buffer, verbose, bufferMax);

		LDL_Console console;

		console.Write(buffer, LDL_CharsLength(buffer));

		LDL_Terminate();
	}
}
#endif

#endif
