/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_BaseRndr_hpp
#define LDL_BaseRndr_hpp

class LDL_BaseRender
{
public:
	LDL_BaseRender(const LDL_Vec2i& size, LDL_Palette* palette);
	const LDL_Vec2i& Size();
	uint8_t ColorIndex();
	const LDL_Color& Color();
	const LDL_Color& Color(uint8_t index);
	void SetColor(uint8_t index);
	void SetColor(const LDL_Color& color);
	LDL_Palette* Palette();
private:
	uint8_t     _paletteColor;
	LDL_Vec2i   _size;
	LDL_Color   _current;
	LDL_Palette _palette;
};

#ifdef LDL_IMPLEMENTATION
LDL_BaseRender::LDL_BaseRender(const LDL_Vec2i& size, LDL_Palette* palette) :
	_paletteColor(0),
	_size(size)
{
	if (palette != NULL)
	{
		for (size_t i = 0; i < LDL_Palette::Max; i++)
		{
			_palette.Set(i, palette->Get(i));
		}
	}
}

const LDL_Vec2i& LDL_BaseRender::Size()
{
	return _size;
}

uint8_t LDL_BaseRender::ColorIndex()
{
	return _paletteColor;
}

const LDL_Color& LDL_BaseRender::Color()
{
	if (!_palette.Empty())
	{
		return Color(_paletteColor);
	}
	else
	{
		return _current;
	}
}

const LDL_Color& LDL_BaseRender::Color(uint8_t index)
{
	_current = _palette.Get(index);

	return _current;
}

void LDL_BaseRender::SetColor(uint8_t index)
{
	_paletteColor = index;
}

void LDL_BaseRender::SetColor(const LDL_Color& color)
{
	_current = color;
}

LDL_Palette* LDL_BaseRender::Palette()
{
	return &_palette;
}
#endif

#endif
