/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_hpp
#define LDL_hpp

#include "Config.hpp"
#include "Bytes.hpp"
#include "Chars.hpp"
#include "Conv.hpp"

#if defined(_WIN32)
    #include "Windows/WinX.hpp"
    #include "Windows/Terminat.hpp"
    #include "Windows/Console.hpp"
    #include "Windows/FileStrm.hpp"
#elif defined(__MSDOS__)
    #include <stdio.h>
    #include <stdlib.h>
    #include <dos.h>
    #include "DOS/Terminat.hpp"
    #include "DOS/Console.hpp"
    #include "DOS/FileStrm.hpp"
#endif

#include "Assert.hpp"
#include "Result.hpp"
#include "Vec2i.hpp"
#include "Color.hpp"
#include "Palette.hpp"
#include "Alpha.hpp"
#include "Test.hpp"
#include "BaseRndr.hpp"
#include "BaseWin.hpp"
#include "BmpLoad.hpp"
#include "Reader.hpp"
#include "ByteRead.hpp"
#include "MemRead.hpp"
#include "Enums.hpp"
#include "Events.hpp"
#include "EventQ.hpp"
#include "EventW.hpp"
#include "Surface.hpp"

#if defined(_WIN32)
    #include "Windows/MainWin.hpp"
    #include "Windows/Ticks.hpp"
    #include "Windows/Library.hpp"
    
    #if defined(LDL_SUPPORT_OPENGL1)
        #include "OpenGL/Mat4f.hpp"
        #include "OpenGL/Funcs.hpp"
        #include "OpenGL/GLFuncs.hpp"
        #include "OpenGL/OpenGL.hpp"
        #include "OpenGL/UtilGL.hpp"
        #include "Windows/GL1Win.hpp"
        typedef LDL_WindowOpenGL1  LDL_Window;
        #include "Renders/GL1Tex.hpp"
        typedef LDL_TextureOpenGL1 LDL_Texture;
        #include "Renders/GL1Rndr.hpp"
        typedef LDL_RenderOpenGL1  LDL_Render;
    #elif defined(LDL_SUPPORT_OPENGL3)
        #include "OpenGL/Mat4f.hpp"
        #include "OpenGL/Funcs.hpp"
        #include "OpenGL/GLFuncs.hpp"
        #include "OpenGL/OpenGL.hpp"
        #include "OpenGL/UtilGL.hpp"
        #include "Windows/GL3Win.hpp"
        typedef LDL_WindowOpenGL3  LDL_Window;
        #include "Renders/GL3Rndr.hpp"
        typedef LDL_TextureOpenGL3 LDL_Texture;
        typedef LDL_RenderOpenGL3  LDL_Render;
    #elif defined(LDL_SUPPORT_SOFTWARE)
        #include "Windows/SoftWin.hpp"
        typedef LDL_WindowSoftware  LDL_Window;
        #include "Renders/SoftTex.hpp"
        typedef LDL_TextureSoftware LDL_Texture;
        #include "Renders/SoftRndr.hpp"
        typedef LDL_RenderSoftware  LDL_Render;
    #endif
#elif defined(__unix__)
    #include "UNIX/Ticks.hpp"
    #include "UNIX/Library.hpp"
#elif defined(__MSDOS__)
    #include "DOS/Ticks.hpp"
    #include "DOS/MainWin.hpp"
    #include "DOS/SoftWin.hpp"
    typedef LDL_WindowSoftware  LDL_Window;
    #include "Renders/SoftTex.hpp"
    typedef LDL_TextureSoftware LDL_Texture;
    #include "Renders/SoftRndr.hpp"
    typedef LDL_RenderSoftware  LDL_Render;
#endif

#include "FpsCount.hpp"

#endif
