/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef LDL_Palette_hpp
#define LDL_Palette_hpp

class LDL_Palette
{
public:
	enum
	{
		Max = 256
	};

	LDL_Palette();
	void Assign(LDL_Palette* palette);
	const LDL_Color& Get(size_t index);
	void Set(size_t index, const LDL_Color& color);
	bool Empty();
private:
	LDL_Color _colors[Max];
	bool      _empty;
};

#ifdef LDL_IMPLEMENTATION
LDL_Palette::LDL_Palette() :
	_empty(true)
{
	LDL_BytesClear(&_colors, 0, sizeof(_colors));
}

void LDL_Palette::Assign(LDL_Palette* palette)
{
	LDL_ASSERT(palette != NULL);

	for (size_t i = 0; i < palette->Max; i++)
	{
		Set(i, palette->Get(i));
	}
}

const LDL_Color& LDL_Palette::Get(size_t index)
{
	LDL_ASSERT(index < Max);

	return _colors[index];
}

void LDL_Palette::Set(size_t index, const LDL_Color& color)
{
	LDL_ASSERT(index < Max);

	_empty         = false;
	_colors[index] = color;
}

bool LDL_Palette::Empty()
{
	return _empty;
}

#endif

#endif
